@url = https://miniature-palm-tree-x7pqvrrvqjq3vqvw-3000.app.github.dev/api/tarefas

GET {{url}}

###
POST {{url}}
Content-Type: application/json

{
    "id": 10,
    "title": "Executar Aplicação"
}

###

GET {{url}}/1